config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ideas do
    resources :reviews, only: [:create, :destroy, :update]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only:[:new, :create] do
     delete :destroy, on: :collection
   end
  resources :ideas do
    resources :likes, only: [:create, :destroy]
  end
  root 'ideas#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.is_admin?
      can :manage, :all
    end

    can [:edit, :destroy], Idea do |idea|
      idea.user == user
    end

    can [:destroy], Review do |review|
      review.user == user
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :title, presence: true, uniqueness: {case_sensitive: false}
  validates(:body,{ presence: true, length: { minimum: 2 } })

  def like_for(user)
  likes.find_by_user_id(user.id)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates :idea_id, uniqueness: {scope: :user_id}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates(:body,{ presence: true, length: { minimum: 3 } })
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :ideas, dependent: :nullify
  has_many :reviews
  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea

  validates(:first_name, { presence: true })
  validates(:last_name, { presence: true })

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                        uniqueness: true,
                        case_sensitive: false,
                        format: VALID_EMAIL_REGEX

  def full_name
    "#{first_name} #{last_name}"
  end                      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def authenticate_user!
    unless user_signed_in?
      flash[:notice] = "Please sign in"
      redirect_to new_session_path
    end
  end

  helper_method :authenticate_user!



  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])

  end
  helper_method :current_user

  





end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @ideas = Idea.last(20)
    @newidea = Idea.new

  end

  #
  # def new
  #   @idea = Idea.new
  # end

  def create

    idea_params = params.require(:idea).permit([:title, :body ])
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to ideas_path
    else
      render :index
    end
  end

  def show
    @idea = Idea.find params[:id]
    @review = Review.new
    @like = @idea.like_for(current_user)
  end

  def destroy
      @idea = Idea.find params[:id]
      if can? :destroy, @idea
       @idea.destroy
       redirect_to ideas_path, notice: 'idea delete'
     else
       redirect_to root_path, alert: 'Access denied'
     end
    end

    def edit
      @idea = Idea.find params[:id]
      redirect_to root_path, alert: 'access denited' unless can? :edit, @idea

    end


    def update
    @idea = Idea.find params[:id]
    idea_params = params.require(:idea).permit([:title, :body])

    if !(can? :edit, @idea)
        redirect_to root_path, alert: 'acess denied'
      elsif @idea.update(idea_params)
        redirect_to idea_path(@idea), notice: 'idea updated'
      else
        render :edit
      end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

    def create
      like = current_user.likes.new
      idea = Idea.find params[:idea_id]
      like.idea = idea
      if like.save
        redirect_to idea_path(idea), notice: "Thanks for liking!"
      else
        redirect_to idea_path(idea), alert: "Can't like! Liked already?"
      end
    end

    def destroy
      idea = Idea.find params[:idea_id]
      like = current_user.likes.find params[:id]
      like.destroy
      redirect_to idea_path(idea), notice: "Like removed!"
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]
  def create
    @idea = Idea.find(params[:idea_id])
    review_params = params.require(:review).permit(:body)
    @review = Review.new(review_params)
    @review.idea = @idea
    @review.user = current_user

    if @review.save
      redirect_to idea_path(@idea), notice: 'Review Created!'
    else
      render '/ideas/show'
    end
  end

  def destroy
    review = Review.find(params[:id])
    if !(can? :destroy, review)
      redirect_to idea_path(review.idea), alert: 'access denied!'
    else
      review.destroy
      redirect_to idea_path(review.idea), notice: 'Review deleted!'
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Signed In!"
      redirect_to root_path
    else
      flash[:alert] = "Could not sign in!"
      render :new
    end
  end

  def destroy
  session[:user_id] = nil
  flash[:notice] = "Signed Out!"
  redirect_to new_session_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id

        flash[:notice] = "User Created!"
        redirect_to ideas_path
      else
        flash[:alert] = "Something went wrong!"
        render :new
    end
  end

    private

    def user_params
      params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= form_for @idea do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>
<div>
    <%= f.label :body %>
    <%= f.text_area :body %>
</div>

<%= f.submit %>

<% end %>

app/views/ideas/index.html.erb
<div>
  <h1 style="display:inline-block">Idea Factory</h1>
  <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">New Post</button>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New Post</h4>
      </div>
      <div class="modal-body">

        <%= @newidea.errors.full_messages.join(', ') %>
        <%= form_for @newidea do |f| %>

        <form>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title %>
          </div>
          <div class="form-group">
            <%= f.label :body %>
            <%= f.text_area :body %>
          </div>
          <div class="form-group">
            <%= f.submit "Create", class:"btn btn-primary" %>

          </div>
        </form>
      </div>

    </div>
  </div>
</div>
<% end %>

<div class="idea">

<% @ideas.each do |idea| %>
<div class="idea_title">

<h3><%= idea.title %></h3>
</div>
<div class="idea_body">
<p><%= idea.body %></p>
</div>

<p><%= idea.user.first_name %></p>
<p>Likes: <%= idea.likes.count %></p>
<%= link_to "View", idea_path(idea), class: 'btn btn-primary' %>
<%= link_to "Join", idea_path(idea), class: 'btn btn-primary' %>
<%= link_to "Like", idea_likes_path(idea), class: 'btn btn-primary', method: :post %>
<hr>
<% end %>

app/views/ideas/show.html.erb
<h1><%= @idea.title %></h1>
<p><%= @idea.body %></p>
<p><%= @idea.user.first_name %></p>
<% if user_signed_in? && @like %>
<%= link_to "Remove Like", idea_like_path(@idea,@like), class: 'btn btn-primary', method: :delete %>
<% else %>
<%= link_to "Like", idea_likes_path(@idea),  class: 'btn btn-primary', method: :post %>
<% end %>



<% if can? :edit, @idea %>
<%= link_to 'Edit', edit_idea_path(@idea) %>
<% end %>
<% if can? :destroy, @idea %>
<%= link_to 'Delete', idea_path(@idea),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
<% end %>



<h2>Reviews</h2>
<%= @review.errors.full_messages.join(', ') %>
<%= form_for [@idea, @review] do |f| %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>
<hr>

<% @idea.reviews.each do |review| %>
<p>Review:<%= review.body %></p>
<p><%= review.user.first_name %></p>
<% if can? :destroy, review %>
<%= link_to 'Delete', idea_review_path(@idea, review),
method: :delete,
data: { confirm: 'Are you sure?'} %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideafactory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <body>
        <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" >Idea Factory</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">

          </ul>

          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
          <li class ="navbar-text">Hello <%=  current_user.first_name%></li>
          <li><%= link_to 'Logout', sessions_path, method: :delete, data: { confirm: 'Logout??'} %></li>
          <% else %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Sign Up', new_user_path %></li>
          <li><%= link_to 'Login', new_session_path %></li>
          <% end %>

          </ul>

          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

        <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger"><%= flash[:alert] %></div>
      <% end %>
<div class="container-fluid">

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

<%= f.submit 'Sign Up', class: 'btn btn-primary'%>

<% end %>